### ISSUE TITLE
Request OBS credentials to automatically fetch the repositories matching the latest Sailfish OS version

### ISSUE THREAD

**Issue by HenkKalkwater** [sailfishos-chum/sailfishos-chum.github.io#12]
Right now, the repos to base the site are hard-coded in the workflow file:

https://github.com/sailfishos-chum/sailfishos-chum.github.io/blob/2a6e8d20afd928424d83ca48c3086823a78b3619/.github/workflows/gen-site.yaml#L30

I'd rather use `obs_user` and `obs_pass`, so it fetches the repositories for the latest Sailfish OS version automatically, so no human is needed to update the GitHub workflow.

### Tasks:
* [ ] Request new OBS credentials
* [ ] Modify the workflow 
* [ ] Put the credentials in https://github.com/sailfishos-chum/sailfishos-chum.github.io/settings/secrets/actions
